FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ngn_wep/GA4_API/sheet_update_custom.py /app/sheet_update_custom.py

ENV RUN_MODE="yesterday"

ENTRYPOINT ["python", "/app/sheet_update_custom.py"]
