FROM python:3.11-slim

WORKDIR /app

# 필요한 파일 복사 및 패키지 설치
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# 필요한 스크립트 복사
COPY ./ngn_wep/cafe24_api/product_catalog_data_handler.py /app/product_catalog_data_handler.py

# 환경변수 설정  
ENV PYTHONUNBUFFERED=1

# 실행 명령어 설정 (토큰 갱신 후 데이터 처리 실행)
ENTRYPOINT ["sh", "-c", "python /app/product_catalog_data_handler.py", "--"]
