FROM python:3.11-slim
WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt && pip install python-dotenv

COPY ./ngn_wep/meta_api/Merge_Meta_Ads_Summary.py /app/Merge_Meta_Ads_Summary.py

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["python", "/app/Merge_Meta_Ads_Summary.py", "yesterday"]
