# Python 3.11 slim 버전 사용
FROM python:3.11-slim

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사 및 설치
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# 프로젝트 관련 파일 복사
COPY ./ngn_wep/cafe24_api/daily_cafe24_sales_handler.py /app/daily_cafe24_sales_handler.py

COPY ./ngn_wep/cafe24_api/orders_handler.py /app/orders_handler.py
COPY config/service-account.json /app/service-account.json

# 환경변수 설정
ENV GOOGLE_APPLICATION_CREDENTIALS="/app/service-account.json"
ENV PYTHONUNBUFFERED=1

# 실행 명령어 설정 (오늘 기준 실행)
ENTRYPOINT ["sh", "-c", "python /app/daily_cafe24_sales_handler.py today"]
