# Python 3.11 slim 버전 사용
FROM python:3.11-slim

# 작업 디렉토리 설정
WORKDIR /app

# requirements.txt 복사 (정확한 경로 지정)
COPY requirements.txt ./

# 의존성 설치
RUN pip install --no-cache-dir -r requirements.txt

# 프로젝트 파일 복사
COPY ./ngn_wep/cafe24_api/cafe24_refund_data_handler.py /app/cafe24_refund_data_handler.py

# 환경 변수 설정
ENV PYTHONUNBUFFERED=1

# 실행 명령어
ENTRYPOINT ["sh", "-c", "python /app/cafe24_refund_data_handler.py \"$1\"", "--"]

# 기본 실행
CMD ["python", "/app/cafe24_refund_data_handler.py"]
